spring:
  application:
    name: rb-spring
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:rb-spring;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
server:
  port: 8080
jwt:
  token:
    header: api_key
    issuer: rb-spring
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 0
naver:
  client:
    id: bLE2aSGt4XW7qhTwZjkJ
    secret : H72K7ES0JW
  book:
    url: https://openapi.naver.com/v1/search/book.json